---
abstract: 'string formatter for logs'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: 0.98
  URI: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-StringFormatter
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Log::StringFormatter:
    file: lib/Log/StringFormatter.pm
    version: 0.01
requires:
  Data::Dumper: 0
  Scalar::Util: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/kazeburo/Log-StringFormatter/issues
  homepage: https://github.com/kazeburo/Log-StringFormatter
  repository: git://github.com/kazeburo/Log-StringFormatter.git
version: 0.01
